### PR TITLE
First translation in Korean

### PR DESCRIPTION
**Pull request by technykim**
made Korean version branch and test commit

### CODE REVIEW

**Comment by PetarKirov** [comment]
Feel free to merge when you feel ready.

**Comment by wilzbach** [comment]
Yep - ideally it's best if another, unbiased person reviews​ the translation - especially in terms of readability. Maybe you do know another Korean D-enthusiast?
Otherwise maybe @mdparker might know someone?

**Comment by mdparker** [comment]
~~Nope, I don't know any fluent Korean speakers who use D~~(actually, I kind of do -- I'll get in touch with him). But with my meager Korean ability I can say, for this little bit, LGTM. I'll ask around, though, for another pair of eyes. My fluency level doesn't stretch far enough to cover all of the translation work to come.

**Comment by technykim** [comment]
I'm a member of D-lang Seoul community(https://dlangseoul.slack.com)
I asked the other Korean members.
At least 3 or 4 guys would join us. :)

**Comment by Geod24** [comment]
We have merged #4 so I am going to close this as outdated.

**Pull request closed without merging**
