### PR TITLE
Request to review and merge my translation works to Korean repository

### PR DESCRIPTION
**Pull request by nidev**
Hi,

I did translation for my own studying on D language, and finally I would like to share my works for anyone who wants to know D.

This PR contains full Korean translations made from D language tour written in English.

I tried to translate from existing working branch, but the last commit of the branch had stopped since May 31. So I made new branch from master and started my works from scratch.

These translations are not reviewed enough yet. Hopefully, I could find Korean enthusiast who can review on somewhere.

Any feedback will be appreciated.

### CODE REVIEW

**Comment by nidev** [comment]
Trailing spaces seemed to be a cause of failure. I made new commit but it does not appear for now.

**Comment by sconeman** [comment]
Great!
I will review this.
Thanks :)

**Comment by Geod24** [comment]
That's a great work. I'm sorry it was not merged earlier.
I have a strong interest in having better support for Korean speakers, so I am going to go ahead and merge this. If you wish to further update it, I'll be happy to review.

**Comment by nidev** [comment]
Thank you, I've been waiting for it!

2019년 6월 4일 (화) 오후 7:42, Mathias LANG <notifications@github.com>님이 작성:

**Comment by Geod24** [comment]
@nidev : I'd be happy to review / merge any further work on this. Moreover, if you are interested in meeting D developers in Seoul, send me an email :)

**Comment by nidev** [comment]
@Geod24 It will be great time to meet other D developers. Thanks for giving me a nice chance, and I'll send you a mail soon.

**Pull request merged**
